openapi: 3.0.3
info:
  title: Product Demo API
  description: API for managing products
  version: 1.0.0

paths:
  /product:
    post:
      summary: Create a new product
      operationId: createProduct
      description: Create a new product
      tags:
        - Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        '200':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Invalid request
        '500':
          description: Internal server error     

components:
  schemas:
    ProductRequest:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: double
          minimum: 0
          exclusiveMinimum: true
      required:
        - name
        - price

    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
          format: double
        createdAt:
          type: string
          format: date
      required:
        - id
        - name
        - price